In [46]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier as KNC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier as DT
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix

In [2]:
#conecting google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
#giving the path of dataset
email=pd.read_csv("/content/drive/MyDrive/ML & AI/emails.csv")

In [5]:
#viewing dataset
email

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0        Email 1    0   0    1    0  ...         0         0   0    0           0
1        Email 2    8  13   24    6  ...         0         0   1    0           0
2        Email 3    0   0    1    0  ...         0         0   0    0           0
3        Email 4    0   5   22    0  ...         0         0   0    0           0
4        Email 5    7   6   17    1  ...         0         0   1    0           0
...          ...  ...  ..  ...  ...  ...       ...       ...  ..  ...         ...
5167  Email 5168    2   2    2    3  ...         0         0   0    0           0
5168  Email 5169   35  27   11    2  ...         0         0   1    0           0
5169  Email 5170    0   0    1    1  ...         0         0   0    0           1
5170  Email 5171    2   7    1    0  ...         0         0   1    0           1
5171  Email 5172   22  24    5    1  ...         0         0   0    0           0

[5172 rows x 3002 columns]

In [6]:
train,test=train_test_split(cca,test_size=0.2)


In [7]:
train

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
3301  Email 3302    3   8    2    2  ...         0         0   0    0           1
4841  Email 4842    5   5    1    1  ...         0         0   1    0           0
3421  Email 3422    1   3    1    2  ...         0         0   0    0           1
4865  Email 4866    3   2    1    0  ...         0         0   0    0           1
2200  Email 2201   12   4    1    3  ...         0         0   4    0           1
...          ...  ...  ..  ...  ...  ...       ...       ...  ..  ...         ...
2839  Email 2840   13  33    5   20  ...         0         0   7    0           1
1123  Email 1124    3   6    1    1  ...         0         0   0    0           0
3516  Email 3517   58  46   17   35  ...         0         0   4    0           1
4052  Email 4053    6  10    7    3  ...         0         0   4    0           0
2519  Email 2520    1   4    1    1  ...         0         0   1    0           1

[4137 rows x 3002 columns]

In [8]:
test

Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
2951  Email 2952    1   4    8    2  ...         0         0   0    0           0
4395  Email 4396    5   2    9    1  ...         0         0   0    0           0
3146  Email 3147    9  15   20    4  ...         0         0   4    0           0
4969  Email 4970   82  67   15   35  ...         0         0   4    0           0
4456  Email 4457    0   0    1    0  ...         0         0   0    0           0
...          ...  ...  ..  ...  ...  ...       ...       ...  ..  ...         ...
3289  Email 3290    0   0    1    0  ...         0         0   0    0           0
1949  Email 1950    1   1    1    0  ...         0         0   0    0           0
3789  Email 3790    0   3    2    0  ...         0         0   0    0           0
657    Email 658   34  31    6   19  ...         0         0   3    0           1
4044  Email 4045   13  12   15    8  ...         0         0   6    0           0

[1035 rows x 3002 columns]

In [11]:
#defining input & output columns using iloc 
trainx=train.iloc[:,1:3001]
trainy=train.iloc[:,3001]
testx=test.iloc[:,1:3001]
testy=test.iloc[:,3001]

**KNN ALGORITHM**

In [12]:
#model building using knn algorithm
modelknn=KNC(n_neighbors=3)
modelknn.fit(trainx,trainy)
predknn=modelknn.predict(testx)
acc=np.mean(predknn==testy)

In [13]:
acc

0.8560386473429952

In [14]:
predknn

array([0, 0, 0, ..., 0, 1, 0])

In [15]:
testy

2951    0
4395    0
3146    0
4969    0
4456    0
       ..
3289    0
1949    0
3789    0
657     1
4044    0
Name: Prediction, Length: 1035, dtype: int64

In [16]:
acc=[]
for i in range(3,50,2):
  modelknn=KNC(n_neighbors=i)
  modelknn.fit(trainx,trainy)
  predknn=modelknn.predict(testx)
  knnacc=np.mean(predknn==testy)
  acc.append([knnacc,i])


In [17]:
acc

[[0.8560386473429952, 3],
 [0.8618357487922705, 5],
 [0.8657004830917875, 7],
 [0.8695652173913043, 9],
 [0.8705314009661835, 11],
 [0.8734299516908213, 13],
 [0.8685990338164251, 15],
 [0.8647342995169082, 17],
 [0.8705314009661835, 19],
 [0.8714975845410629, 21],
 [0.8753623188405797, 23],
 [0.8695652173913043, 25],
 [0.8676328502415459, 27],
 [0.8676328502415459, 29],
 [0.8676328502415459, 31],
 [0.8657004830917875, 33],
 [0.8676328502415459, 35],
 [0.8743961352657005, 37],
 [0.8676328502415459, 39],
 [0.8695652173913043, 41],
 [0.8685990338164251, 43],
 [0.8628019323671497, 45],
 [0.863768115942029, 47],
 [0.8608695652173913, 49]]

**LOGISTIC REGRESSION ALGORITHM**

In [20]:
#model building using Logistic Regression Algorithm
logistic_regression=LogisticRegression()
logistic_regression.fit(trainx,trainy)
y_pred=logistic_regression.predict(testx)
acc=np.mean(y_pred==testy)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [21]:
acc

0.9739130434782609

**DECISION TREE ALGORITHM**

In [26]:
#model buidling using Decision Tree Algorithm
modelDT=DT(criterion="entropy")
modelDT.fit(trainx,trainy)
predDT=modelDT.predict(testx)
DTacc=np.mean(predDT==testy)

In [27]:
DTacc

0.9429951690821256

**RANDOM FOREST ALGORITHM**

In [29]:
#model building using Random Forest Algorithm (3001 is the number of columns)
modelRFC=RFC(n_jobs=3001,n_estimators=50,oob_score=True,criterion="entropy")
modelRFC.fit(trainx,trainy)
predRFC=modelRFC.predict(testx)
RFCacc=np.mean(predRFC==testy)

In [30]:
RFCacc

0.9729468599033816

**SUPPORT VECTOR MACHINE** **- Linear Method**

In [32]:
#model buidling using SVM Algorithm (Method 1 - Linear)
model_linear=SVC(kernel="linear")
model_linear.fit(trainx,trainy)
pred_test_linear=model_linear.predict(testx)
acclinear=np.mean(pred_test_linear==testy)

In [33]:
acclinear

0.9594202898550724

**SUPPORT VECTOR MACHINE** **- Polynomial Method**

In [34]:
#model buidling using SVM Algorithm (Method 2 - Polynomial)
model_poly=SVC(kernel="poly")
model_poly.fit(trainx,trainy)
pred_test_poly=model_poly.predict(testx)
accpoly=np.mean(pred_test_poly==testy)

In [36]:
accpoly

0.7739130434782608

**SUPPORT VECTOR MACHINE** **- RBF Method**

In [37]:
#model buidling using SVM Algorithm (Method 3 - RBF)
model_RBF=SVC(kernel="rbf")
model_RBF.fit(trainx,trainy)
pred_test_RBF=model_RBF.predict(testx)
accRBF=np.mean(pred_test_RBF==testy)

In [40]:
accRBF

0.8183574879227054

**SUPPORT VECTOR MACHINE** **- Sigmoid Method**

In [44]:
#model buidling using SVM Algorithm (Method 4 - Sigmoid)
model_sigmoid=SVC(kernel="sigmoid")
model_sigmoid.fit(trainx,trainy)
pred_test_sigmoid=model_sigmoid.predict(testx)
accsigmoid=np.mean(pred_test_sigmoid==testy)

In [45]:
accsigmoid

0.6154589371980677

**NAIVE BAYES ALGORITHM**

In [47]:
ignb=GaussianNB()
imnb=MultinomialNB()
ibnb=BernoulliNB()

In [49]:
#building and predicting at the same time
pred_gnb=ignb.fit(trainx,trainy).predict(testx)
pred_mnb=imnb.fit(trainx,trainy).predict(testx)
pred_bnb=ibnb.fit(trainx,trainy).predict(testx)

In [59]:
#model buidling using Naive Bayes Algorithm (Confusion Matrix GausisionNB Model)
CM=confusion_matrix(testy,pred_gnb)
accemailgnb=np.mean(pred_gnb==testy.values.flatten())

In [53]:
CM

array([[725,  32],
       [ 16, 262]])

In [60]:
accemailgnb

0.9536231884057971

In [70]:
#model buidling using Naive Bayes Algorithm (Confusion Matrix Multinomial Model)
CM=confusion_matrix(testy,pred_mnb)
accemailmnb=np.mean(pred_mnb==testy.values.flatten())

In [71]:
CM

array([[724,  33],
       [ 15, 263]])

In [72]:
accemailmnb

0.9536231884057971

In [67]:
#model buidling using Naive Bayes Algorithm (Confusion Matrix Bernoulli Model)
CM=confusion_matrix(testy,pred_bnb)
accemailbnb=np.mean(pred_bnb==testy.values.flatten())

In [68]:
CM

array([[705,  52],
       [ 59, 219]])

In [69]:
accemailbnb

0.8927536231884058